version: "3.9"

services:
  backend:
    restart: always
    image: kenbsq/drc-backend
    container_name: readiness-challenge-backend
    #volumes:
    # - /app/node_modules
    # don't overwrite node_modules in container with local node modules
    # - ./server:/app
    # this a must for local development so that code changes are reflected real time
    # without the need to rebuild whole image
    # local:container
    ports:
      - 5000:5000
    # local:container
    depends_on:
      # - mongodb
      - cache
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${MONGO_URI}
      REDIS_HOST: cache
      REDIS_PORT: 6379
    networks:
      - library-mern-api

  cache:
    image: redis:latest
    restart: always
    # ports:
    #   - "6378:6379"
    volumes:
      - cache:/data
    networks:
      - library-mern-api

  web-scraper:
    image: kenbsq/drc-web-scraper
    depends_on:
      - cache
    networks:
      - library-mern-api

  deriv-data-processor:
    image: kenbsq/drc-deriv-data-processor
    depends_on:
      - cache
    networks:
      - library-mern-api

  cryptocompare-data-processor:
    image: kenbsq/drc-cryptocompare-data-processor
    depends_on:
      - cache
    networks:
      - library-mern-api

  forex-homepage-data:
    image: kenbsq/drc-forex-homepage-data
    depends_on:
      - cache
    networks:
      - library-mern-api

  client:
    restart: always
    image: kenbsq/drc-client

    container_name: readiness-challenge-frontend
    # ports:
    #   - 3001:3000
    depends_on:
      - backend
    networks:
      - library-mern-api

  nginx:
    restart: always
    depends_on:
      - backend
      - client
    image: kenbsq/drc-nginx
    ports:
      - 8080:80
    networks:
      - library-mern-api

networks:
  library-mern-api:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
  cache:
    driver: local
